// Núcleo de pontos: lançamento (award) transacional e idempotente por evento,
// configuração versionada e os contadores agregados do painel. A API (src/api)
// usa daqui; o seed dos emuladores carrega o build (functions/lib/points).
export {
  ALREADY_EXISTS,
  applyAwards,
  centralFromDoc,
  centralPointsRef,
  ledgerRef,
  planAwards,
  requireFan,
  retryOnAlreadyExists,
  runAward,
  walletFromDoc,
  walletRef,
  type AwardContext,
  type AwardPlan,
  type FanAwards,
  type FanContext,
} from './award';
export {
  CONFIG_TTL_MS,
  ConfigValidationError,
  createConfigSource,
  DEFAULT_POINTS_CONFIG,
  DEFAULT_SEASON_CONFIG,
  parsePointsConfig,
  parseSeasonConfig,
  pointsConfigRef,
  seasonConfigRef,
  staticConfigSource,
  validatePointsConfigInput,
  validateSeasonInput,
  type ConfigSource,
  type LoadedConfig,
  type SeasonConfig,
} from './config';
export {
  dayKey,
  EARN_SOURCES,
  levelForXp,
  ledgerId,
  PointsError,
  TIME_ZONE,
  weekKey,
  type Actor,
  type AwardEntry,
  type AwardResult,
  type EarnSource,
  type Level,
  type PointsConfig,
  type SeasonInfo,
  type WalletState,
} from './model';
export { seedCamilaWallet, CAMILA_SEED } from './seed';
export { pickShard, SHARD_COUNT, shardRef } from './stats';
export {
  decodeLedgerCursor,
  encodeLedgerCursor,
  LEDGER_LIMIT_DEFAULT,
  LEDGER_LIMIT_MAX,
  progressView,
  readLedgerPage,
  readWallet,
  walletView,
  type LedgerItem,
  type LedgerPage,
  type ProgressView,
  type WalletView,
} from './wallet';
