// Perfil editável do fã (bloco 9): a troca do @ e a foto pela API, a fila que
// acerta as cópias do nome e da foto nos comentários, a pasta da foto na
// exclusão de conta e o seed da foto de teste. A API (src/api/routes/
// profile.ts) e o gatilho usam daqui; o seed dos emuladores e o
// scripts/release-fan-username.mjs carregam o build (functions/lib/fan-profile).
// docs/arquitetura-api.md, seção 24. Desde o perfil novo (seção 28): a bio, o
// gênero, a conta privada e as redes (details.ts), a edição inteira pelo
// `PUT /me/profile`, o perfil público (`GET /fans/:fanId`), o
// `clearFanProfileText` da Moderação e os fãs de teste com os detalhes.
export {
  BIO_MAX,
  BIO_MAX_LINES,
  editableProfileOf,
  FAN_CITY_MAX,
  GENDERS,
  genderOf,
  hasProfileChanges,
  isSocialHandle,
  normalizeSocialHandle,
  parseProfileChanges,
  PROFILE_CHANGE_KEYS,
  profileDiff,
  profileUpdateOf,
  publicProfileOf,
  SOCIAL_INPUT_MAX,
  SOCIAL_NETWORKS,
  SOCIAL_PATTERNS,
  socialsOf,
  type FanSocials,
  type Gender,
  type ParsedProfileChanges,
  type ProfileChanges,
  type ProfileInvalidField,
  type ProfileInvalidReason,
  type SocialHandleResult,
  type SocialNetwork,
  type SocialProblem,
} from './details';
export { fanPhotoFiles, MISSING_FAN_PHOTO_FILES, type FanPhotoFiles } from './files';
export {
  ABANDONED_UPLOAD_MS,
  AUTOMATIC_USERNAME,
  FAN_PHOTO_PATH,
  FAN_PHOTO_PURGE_DELAY_MS,
  FAN_PROFILE_SLOW_WINDOW_MS,
  FAN_PROFILE_SYNC_DAILY_WINDOWS,
  FAN_PROFILE_SYNC_WINDOW_MS,
  NAME_CHANGES_PER_DAY,
  normalizeUsername,
  parseFanPhotoPath,
  PHOTO_CHANGES_PER_DAY,
  PHOTO_HEAD_BYTES,
  PHOTO_MAX_BYTES,
  PHOTO_MAX_SIDE,
  PHOTO_UPLOAD_MAX_AGE_MS,
  PHOTO_UPLOAD_RENEW_MS,
  PHOTO_UPLOAD_SLOT_MS,
  PHOTO_UPLOADS_PER_DAY,
  PROFILE_SAVES_PER_DAY,
  PROFILE_SYNC_PAGE,
  ProfileEditError,
  USERNAME_CHANGE_INTERVAL_MS,
  USERNAME_INPUT_MAX,
  USERNAME_PATTERN,
  usernameChangeProblem,
  UsernameReleaseError,
  usernameRefusal,
  type ProfileEditErrorReason,
  type UsernameReleaseReason,
} from './model';
export {
  clearFanPhoto,
  clearFanProfileText,
  findFanByEmail,
  parseCurrentUsername,
  parseLookupEmail,
  parseProfileTextFields,
  PROFILE_TEXT_FIELDS,
  resetFanUsername,
  type FanPanelDeps,
  type ProfileTextField,
} from './panel';
export {
  countFanSearchKeys,
  fanSearchKeys,
  normalizeSearch,
  sameSearchKeys,
  searchKeysOf,
  writeFanSearchKeys,
} from './search';
export {
  SEED_FAN_DETAILS,
  SEED_FANS,
  SEED_PHOTO_FILE,
  SEED_SPAM_PHOTO_FILE,
  seedFanDetails,
  seedFanDetailsChanges,
  seedFanPhoto,
  type SeedFan,
  type SeedFanDetails,
  type UploadPhoto,
} from './seed';
export {
  changeUsername,
  photoUploadSlotRef,
  purgeFanPhotos,
  readFanPublicProfile,
  readUsernameAvailability,
  readUsernameSwap,
  releaseUsername,
  releaseUsernameIn,
  removeFanPhoto,
  removeReplacedPhoto,
  reservePhotoUpload,
  setFanPhoto,
  syncFanProfile,
  updateFanProfile,
  writeUsernameSwap,
  type FanProfileSyncResult,
  type PhotoChange,
  type PhotoUploadSlot,
  type UsernameAvailability,
  type UsernameChange,
  type UsernameRelease,
  type UsernameStatus,
  type UsernameSwap,
  type UsernameSwapFields,
} from './service';
export {
  FAN_PROFILE_MAX_ATTEMPTS,
  FAN_PROFILE_QUEUE,
  profileSyncBudgetRef,
  queueFanPhotoPurge,
  queueFanProfileSync,
  runFanProfileSync,
  syncFanSearchKeys,
  type FanProfileQueue,
  type QueueFanProfileSyncResult,
} from './sync';
