// Centrais de verdade (bloco 4): o vínculo do fã com as centrais, o fanCount
// em shards copiado pela fila syncArtistFanCount, as leituras das rotas e o
// seed. A API (src/api/routes/centrals.ts) usa daqui; o seed dos emuladores
// carrega o build (functions/lib/centrals).
export {
  artistDetailsView,
  artistRecord,
  artistView,
  CENTRAL_ENTRIES_PER_DAY,
  CENTRALS_MAX,
  CentralError,
  coverOf,
  exceedsEntryLimit,
  FAN_COUNT_WINDOW_MS,
  FAN_SHARD_COUNT,
  fanCentralView,
  fanCountSyncTask,
  fanShardOf,
  FOLLOW_MAX,
  isArtistId,
  isPublished,
  memberFanCount,
  parseFollowArtistIds,
  shouldCopyFanCount,
  sortFanCentrals,
  sumFanShards,
  type ArtistRecord,
  type CentralErrorReason,
  type JoinVia,
} from './model';
export {
  artistRef,
  centralPointsAggregate,
  fanShardRef,
  fanShardsRef,
  followedAfter,
  joinCentrals,
  leaveAllCentrals,
  leaveCentral,
  membershipRef,
  membershipsRef,
  readArtistDetails,
  readFanCentrals,
  readFanCountForDelete,
  readFollow,
  readJoin,
  readPublishedArtists,
  runJoinCentrals,
  sumCentralPoints,
  syncFanCount,
  type ArtistPostCounter,
  type CentralPointsAggregate,
  type FanCountSync,
  type JoinOutcome,
  type JoinRead,
} from './service';
export { CAMILA_CENTRALS, SEED_CENTRALS, seedCamilaCentrals, seedCentrals } from './seed';
export {
  FAN_COUNT_MAX_ATTEMPTS,
  FAN_COUNT_QUEUE,
  queueFanCountSync,
  runFanCountSync,
  type FanCountQueue,
} from './sync';
