// Convite com atribuição e origem do fã (bloco 5): o código de cada fã, o
// claim, a visita no app, os links compartilhados, a exclusão de conta e o
// seed. A API (src/api/routes/invites.ts) usa daqui; o seed dos emuladores
// carrega o build (functions/lib/invites).
export { INVITE_KEY_SECRET } from './config';
export {
  classifyInvitePath,
  drawInviteCode,
  INVITE_CLAIM_WINDOW_MS,
  INVITE_CODE_ALPHABET,
  INVITE_CODE_DRAWS,
  INVITE_CODE_LENGTH,
  INVITE_LINK_BASE,
  INVITE_LINKS_PER_DAY,
  INVITE_VISITS_SENT_PER_DAY,
  InviteError,
  inviteOwnership,
  inviteUrl,
  isInviteOwner,
  isWithinClaimWindow,
  normalizeEmail,
  normalizeInviteCode,
  normalizeUtm,
  originKind,
  parseClaimBody,
  parseLinkId,
  parseVisitBody,
  personKey,
  type ClaimInput,
  type ClaimVia,
  type InviteErrorReason,
  type InviteLinkKind,
  type InviteLinkOrigin,
  type InviteUtm,
  type Parsed,
  type ReferralAwardStatus,
  type SharedLink,
  type SharedLinkKind,
  type VisitInput,
} from './model';
export {
  CAMILA_INVITE_CODE,
  CAMILA_INVITE_LINKS,
  EMULATOR_INVITE_KEY,
  SEED_INVITEES,
  seedCamilaInvite,
  seedClaimInput,
  seedInviteClaims,
  type SeedInviteOrigin,
} from './seed';
export {
  claimInvite,
  countInviteStats,
  detachReferrals,
  ensureInviteCode,
  fanInviteRef,
  inviteCodeRef,
  inviteLinkRef,
  inviteLinksRef,
  inviteVisitorRef,
  recordInviteLink,
  recordInviteVisit,
  referralRef,
  referralsRef,
  removeInviteData,
  runClaim,
  runInviteLinks,
  type ClaimOutcome,
  type InviteCaller,
  type InviteWork,
  type LinkOutcome,
  type VisitOutcome,
} from './service';
